### ISSUE TITLE
potential issue in sleeping

### ISSUE THREAD

**Issue by martingartonft** [Financial-Times/notifications-push#6]
eventDispatcher.receiveEvents has a sleep at the end.

I believe this means there will always be a 30s delay between publishes, regardless of when they happened.

In other words, 10 quick publishes will not result in a 30s delay followed by 10 quick events, it will result in 30s, 1 publish, 30s, 1 publish etc.

Disclaimer: I have not reproduced this behaviour - This is from code inspection alone.

**Comment by Nesze** [comment]
Messages are processed concurrently, so for every new message the receiveEvents functions is spawned as a separate go routine. 
However, this can result in out-of-order messages, so we probably have to fix this.

**Comment by martingartonft** [comment]
you could turn off concurrency in gonsumer and instead have 1 goroutine in this app handling the 30s delays.  Just an idea.

**Comment by Nesze** [comment]
I think that's not possible with the current implementation of the gonsumer lib. Currently it expects a handler function, which processes only one message at a time. So without modifying the lib, what I can do against out-of-order delivery with minor modifications is: https://github.com/Financial-Times/notifications-push/pull/7.

(Without touching the gonsumer) To place the sleep logic in one place, there should be a msg reaggregation logic somewhere which sounds quite complicated.

**Comment by martingartonft** [comment]
I think your change does handle this using the current implementation of gonsumer?
It moves the problem into this app (where it belongs) and we can iterate to a better solution here.
I mean there is no longer a problem at all regarding ordering or delays that is the fault of the gonsumer lib or that needs changes to it.

**Comment by Nesze** [comment]
I also think it's better now.
It would have been neat though, to have support for a queue msg handler function with a signature like `handler (msg []consumer.Message)` so then the sleep logic would have been in one go routine.
